# sudo: required
# services:
#   - docker
# install:
#   - docker build --tag fontforge .travis
# script:
#   - docker run --volume $(pwd):/FiraMath/work fontforge
#     python ./scripts/build.py --fonts
sudo: required
language: python
python:
  - "2.7"
install:
  - sudo apt-get update
  - sudo apt-get install --yes python-fontforge
before_script:
  - chmod --verbose +x ./scripts/*.py
script:
  - ./scripts/build.py --fonts
