sudo: required
services:
  - docker
install:
  - mkdir -p ./release/fonts
  - docker build --tag fontforge .travis
script:
  - docker run --volume $(pwd):/home/firamath/work fontforge python ./scripts/build.py --fonts
  - docker run --volume $(pwd):/home/firamath/work fontforge python ./scripts/build.py --check
